services:
  # 1. Бэкенд NestJS (Веб-сервис)
  - type: web
    name: atlas-fleet-backend
    env: node
    plan: free
    region: frankfurt # Переносим сервер во Франкфурт
    buildCommand: npm install --include=dev && npm run --prefix apps/backend prisma:generate && npm run --prefix apps/backend build
    startCommand: npm run --prefix apps/backend start:prod
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_EXPIRES_IN
        value: 7d
      - key: TELEGRAM_BOT_TOKEN
        value: 8766839286:AAEqWXCUPF3wHrXci7fIH0KqCiSFi98UKbQ
      - key: TELEGRAM_BOT_USERNAME
        value: atlas_fllet_bot
      - key: DATABASE_URL
        sync: false

  # 2. Telegram-бот Telegraf (Веб-сервис для работы на бесплатном тарифе)
  - type: web
    name: atlas-fleet-bot
    env: node
    plan: free
    region: frankfurt # Переносим бота во Франкфурт
    buildCommand: npm install --include=dev && npm run --prefix apps/backend prisma:generate && npm run --prefix apps/bot build
    startCommand: npm run --prefix apps/bot start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8766839286:AAEqWXCUPF3wHrXci7fIH0KqCiSFi98UKbQ
      - key: TELEGRAM_BOT_USERNAME
        value: atlas_fllet_bot
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_MINIAPP_URL
        sync: false
